### ISSUE TITLE
Scala 2.12 artifact

### ISSUE THREAD

**Issue by protheusfr** [outr/neo4akka#2]
Hi,

I'm interested by your testing project.
I've tried to get Scala 2.12 artifact but despite the documentation it doesn't seem available nor from Maven Central or Sonatype.

**Comment by darkfrog26** [comment]
I haven't been able to get it to compile on 2.12 because neo4j (which I'm relying on their internal library for Cypher parsing at compile-time) actually is mostly written in Scala now, but they depend on Scala 2.11.  I just updated to the latest version, but it still relies on 2.11.  I've actually completely abandoned this project and neo4j because of their licensing, lack of functionality in the open-source version (no clustering), and their terrible pricing model for their enterprise version.

I've switched to ArangoDB and absolutely love it.  If you're interested you can take a look at my library that's a work-in-progress here: https://github.com/outr/arangodb-scala

I'd welcome any contributions to either project.  I've pushed my changes to neo4akka, so you're welcome to play around and see if you can make it work on 2.12, but I'm not sure it's technically possible.

**Comment by protheusfr** [comment]
Thanks you for your response, I'm a little but sad to read that Neo4j is losing interest due to an agressive commercial strategy.
I recognize I don't know Arango DB (I'm working with Neo4j since many years).
I will take a look on it, thank you for info.
